title: Felipe Meireles
description: Senior SAP Developer | ABAP Cloud | S/4HANA | SAP BTP | Fiori/UI5 | Integration

theme: just-the-docs

url: https://meireleslipe.github.io

color_scheme: dark

search_enabled: true

heading_anchors: true

back_to_top: true
back_to_top_text: "Voltar ao topo"

aux_links:
  GitHub: https://github.com/meireleslipe
  LinkedIn: https://www.linkedin.com/

aux_links_new_tab: true

footer_content: "Felipe Meireles · SAP Developer Technical Portfolio"
